### ISSUE TITLE
Missing assets/biglogo-red.png

### ISSUE THREAD

**Issue by OrientalHorizon** [WunschUnreif/Latex-Templates#1]
您好，我在使用 wpre 主题的时候被 cannot find assets/biglogo-red.png 困扰了很久，找了半天才发现一些 .sty 文件中有如下内容：
```
\def\wpre@outer@options{%
    framelogo = {
        initial = assets/biglogo-red.png
    },
}
```
然后 repo 的 assets 文件夹下有一个 .gitignore 文件，当中列着 *.png。也就是说您把 biglogo-red.png ignore 掉了。

建议在 README.md 或者 wpre/README.md 中表明这一点，避免使用者苦于寻找 cannot find assets/biglogo-red.png 的报错原因；或者上传一下 assets/biglogo-red.png。

**Comment by WunschUnreif** [comment]
感谢您提出的Issue，我在 58619e0453004bcde89c59765b66c11e2f342aa3 中将 `titlelogo` 和 `framelogo` 的初始值改为了 `{}`，并在 demo 中使用 `mwe` 包提供的占位图片替代了原来的 `biglogo-red.png`，目前应该可以直接编译通过。
